//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOnt.OServiceConfiguration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OServiceConfiguration.OServiceConfigurationSoap")]
    public interface OServiceConfigurationSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Type_Object", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Type_Object();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Type_Object", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Type_ObjectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Type_Class", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Type_Class();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Type_Class", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Type_ClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Type_AttributeType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Type_AttributeType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Type_AttributeType", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Type_AttributeTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Type_RelationType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Type_RelationType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Type_RelationType", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Type_RelationTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OLogStates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceConfiguration.clsLogStates OLogStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OLogStates", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsLogStates> OLogStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OMappingRules", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceConfiguration.clsMappingRules OMappingRules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OMappingRules", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsMappingRules> OMappingRulesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ORelationRules", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceConfiguration.clsOntologyRelationRules ORelationRules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ORelationRules", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsOntologyRelationRules> ORelationRulesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVariables", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceConfiguration.clsVariables OVariables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OVariables", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsVariables> OVariablesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ODirections", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceConfiguration.clsDirections ODirections();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ODirections", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsDirections> ODirectionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceConfiguration.clsFields OFields();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OFields", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsFields> OFieldsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Config", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfOnt.OServiceConfiguration.Config[] Config();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Config", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.Config[]> ConfigAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegExGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RegExGuid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegExGuid", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RegExGuidAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsLogStates : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clsOntologyItem logState_SuccessField;
        
        private clsOntologyItem logState_ErrorField;
        
        private clsOntologyItem logState_NothingField;
        
        private clsOntologyItem logState_InsertField;
        
        private clsOntologyItem logState_UpdateField;
        
        private clsOntologyItem logState_DeleteField;
        
        private clsOntologyItem logState_RelationField;
        
        private clsOntologyItem logState_ExistsField;
        
        private clsOntologyItem[] logStatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public clsOntologyItem LogState_Success {
            get {
                return this.logState_SuccessField;
            }
            set {
                this.logState_SuccessField = value;
                this.RaisePropertyChanged("LogState_Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public clsOntologyItem LogState_Error {
            get {
                return this.logState_ErrorField;
            }
            set {
                this.logState_ErrorField = value;
                this.RaisePropertyChanged("LogState_Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public clsOntologyItem LogState_Nothing {
            get {
                return this.logState_NothingField;
            }
            set {
                this.logState_NothingField = value;
                this.RaisePropertyChanged("LogState_Nothing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public clsOntologyItem LogState_Insert {
            get {
                return this.logState_InsertField;
            }
            set {
                this.logState_InsertField = value;
                this.RaisePropertyChanged("LogState_Insert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public clsOntologyItem LogState_Update {
            get {
                return this.logState_UpdateField;
            }
            set {
                this.logState_UpdateField = value;
                this.RaisePropertyChanged("LogState_Update");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public clsOntologyItem LogState_Delete {
            get {
                return this.logState_DeleteField;
            }
            set {
                this.logState_DeleteField = value;
                this.RaisePropertyChanged("LogState_Delete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public clsOntologyItem LogState_Relation {
            get {
                return this.logState_RelationField;
            }
            set {
                this.logState_RelationField = value;
                this.RaisePropertyChanged("LogState_Relation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public clsOntologyItem LogState_Exists {
            get {
                return this.logState_ExistsField;
            }
            set {
                this.logState_ExistsField = value;
                this.RaisePropertyChanged("LogState_Exists");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public clsOntologyItem[] LogStates {
            get {
                return this.logStatesField;
            }
            set {
                this.logStatesField = value;
                this.RaisePropertyChanged("LogStates");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsOntologyItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clsOntologyItem[] oList_RelField;
        
        private string gUIDField;
        
        private string iD_ItemField;
        
        private string iD_ParentField;
        
        private string iD_ClassField;
        
        private string iD_DataTypeField;
        
        private string gUID_ParentField;
        
        private string gUID_RelatedField;
        
        private string gUID_RelationField;
        
        private string nameField;
        
        private string name_ItemField;
        
        private string name_ParentField;
        
        private string captionField;
        
        private string additional1Field;
        
        private string additional2Field;
        
        private string typeField;
        
        private string filterField;
        
        private System.Nullable<int> imageIDField;
        
        private System.Nullable<int> versionField;
        
        private System.Nullable<long> levelField;
        
        private System.Nullable<bool> new_ItemField;
        
        private System.Nullable<bool> deletedField;
        
        private System.Nullable<bool> markField;
        
        private System.Nullable<bool> objectReferenceField;
        
        private System.Nullable<int> directionField;
        
        private System.Nullable<long> minField;
        
        private System.Nullable<long> max1Field;
        
        private System.Nullable<long> max2Field;
        
        private System.Nullable<long> val_LongField;
        
        private System.Nullable<bool> val_BoolField;
        
        private System.Nullable<System.DateTime> val_DateField;
        
        private System.Nullable<double> val_RealField;
        
        private string val_StringField;
        
        private System.Nullable<long> countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public clsOntologyItem[] OList_Rel {
            get {
                return this.oList_RelField;
            }
            set {
                this.oList_RelField = value;
                this.RaisePropertyChanged("OList_Rel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ID_Item {
            get {
                return this.iD_ItemField;
            }
            set {
                this.iD_ItemField = value;
                this.RaisePropertyChanged("ID_Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ID_Parent {
            get {
                return this.iD_ParentField;
            }
            set {
                this.iD_ParentField = value;
                this.RaisePropertyChanged("ID_Parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ID_Class {
            get {
                return this.iD_ClassField;
            }
            set {
                this.iD_ClassField = value;
                this.RaisePropertyChanged("ID_Class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ID_DataType {
            get {
                return this.iD_DataTypeField;
            }
            set {
                this.iD_DataTypeField = value;
                this.RaisePropertyChanged("ID_DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string GUID_Parent {
            get {
                return this.gUID_ParentField;
            }
            set {
                this.gUID_ParentField = value;
                this.RaisePropertyChanged("GUID_Parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string GUID_Related {
            get {
                return this.gUID_RelatedField;
            }
            set {
                this.gUID_RelatedField = value;
                this.RaisePropertyChanged("GUID_Related");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string GUID_Relation {
            get {
                return this.gUID_RelationField;
            }
            set {
                this.gUID_RelationField = value;
                this.RaisePropertyChanged("GUID_Relation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Name_Item {
            get {
                return this.name_ItemField;
            }
            set {
                this.name_ItemField = value;
                this.RaisePropertyChanged("Name_Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Name_Parent {
            get {
                return this.name_ParentField;
            }
            set {
                this.name_ParentField = value;
                this.RaisePropertyChanged("Name_Parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Caption {
            get {
                return this.captionField;
            }
            set {
                this.captionField = value;
                this.RaisePropertyChanged("Caption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Additional1 {
            get {
                return this.additional1Field;
            }
            set {
                this.additional1Field = value;
                this.RaisePropertyChanged("Additional1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Additional2 {
            get {
                return this.additional2Field;
            }
            set {
                this.additional2Field = value;
                this.RaisePropertyChanged("Additional2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("Filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> ImageID {
            get {
                return this.imageIDField;
            }
            set {
                this.imageIDField = value;
                this.RaisePropertyChanged("ImageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<int> Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<long> Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<bool> New_Item {
            get {
                return this.new_ItemField;
            }
            set {
                this.new_ItemField = value;
                this.RaisePropertyChanged("New_Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<bool> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<bool> Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
                this.RaisePropertyChanged("Mark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<bool> ObjectReference {
            get {
                return this.objectReferenceField;
            }
            set {
                this.objectReferenceField = value;
                this.RaisePropertyChanged("ObjectReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<int> Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<long> Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("Min");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public System.Nullable<long> Max1 {
            get {
                return this.max1Field;
            }
            set {
                this.max1Field = value;
                this.RaisePropertyChanged("Max1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<long> Max2 {
            get {
                return this.max2Field;
            }
            set {
                this.max2Field = value;
                this.RaisePropertyChanged("Max2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<long> Val_Long {
            get {
                return this.val_LongField;
            }
            set {
                this.val_LongField = value;
                this.RaisePropertyChanged("Val_Long");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<bool> Val_Bool {
            get {
                return this.val_BoolField;
            }
            set {
                this.val_BoolField = value;
                this.RaisePropertyChanged("Val_Bool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<System.DateTime> Val_Date {
            get {
                return this.val_DateField;
            }
            set {
                this.val_DateField = value;
                this.RaisePropertyChanged("Val_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<double> Val_Real {
            get {
                return this.val_RealField;
            }
            set {
                this.val_RealField = value;
                this.RaisePropertyChanged("Val_Real");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Val_String {
            get {
                return this.val_StringField;
            }
            set {
                this.val_StringField = value;
                this.RaisePropertyChanged("Val_String");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<long> Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Config : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string configItemField;
        
        private string configValueStringField;
        
        private int configValueIntField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ConfigItem {
            get {
                return this.configItemField;
            }
            set {
                this.configItemField = value;
                this.RaisePropertyChanged("ConfigItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ConfigValueString {
            get {
                return this.configValueStringField;
            }
            set {
                this.configValueStringField = value;
                this.RaisePropertyChanged("ConfigValueString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ConfigValueInt {
            get {
                return this.configValueIntField;
            }
            set {
                this.configValueIntField = value;
                this.RaisePropertyChanged("ConfigValueInt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsFields : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsDirections : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clsOntologyItem direction_LeftRightField;
        
        private clsOntologyItem direction_RightLeftField;
        
        private clsOntologyItem[] directionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public clsOntologyItem Direction_LeftRight {
            get {
                return this.direction_LeftRightField;
            }
            set {
                this.direction_LeftRightField = value;
                this.RaisePropertyChanged("Direction_LeftRight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public clsOntologyItem Direction_RightLeft {
            get {
                return this.direction_RightLeftField;
            }
            set {
                this.direction_RightLeftField = value;
                this.RaisePropertyChanged("Direction_RightLeft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public clsOntologyItem[] Directions {
            get {
                return this.directionsField;
            }
            set {
                this.directionsField = value;
                this.RaisePropertyChanged("Directions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsVariables : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clsOntologyItem variable_ID_ITEMField;
        
        private clsOntologyItem variable_NAME_ITEMField;
        
        private clsOntologyItem variable_ID_PARENTField;
        
        private clsOntologyItem variable_ITEMLISTField;
        
        private clsOntologyItem variable_ID_CLASSField;
        
        private clsOntologyItem variable_ID_ATTRIBUTETYPEField;
        
        private clsOntologyItem variable_ID_DATATYPEField;
        
        private clsOntologyItem variable_MINField;
        
        private clsOntologyItem variable_MAXField;
        
        private clsOntologyItem variable_ID_CLASS_LEFTField;
        
        private clsOntologyItem variable_ID_CLASS_RIGHTField;
        
        private clsOntologyItem variable_ID_RELATIONTYPEField;
        
        private clsOntologyItem variable_ONTOLOGYField;
        
        private clsOntologyItem variable_MIN_FORWField;
        
        private clsOntologyItem variable_MAX_FORWField;
        
        private clsOntologyItem variable_MAX_BACKWField;
        
        private clsOntologyItem variable_ID_ATTRIBUTEField;
        
        private clsOntologyItem variable_ID_OBJECTField;
        
        private clsOntologyItem variable_ORDERIDField;
        
        private clsOntologyItem variable_VAL_NAMEDField;
        
        private clsOntologyItem variable_VAL_BITField;
        
        private clsOntologyItem variable_VAL_DATEField;
        
        private clsOntologyItem variable_VAL_DOUBLEField;
        
        private clsOntologyItem variable_VAL_LNGField;
        
        private clsOntologyItem variable_VAL_STRINGField;
        
        private clsOntologyItem variable_ID_PARENT_OBJECTField;
        
        private clsOntologyItem variable_ID_OTHERField;
        
        private clsOntologyItem variable_ID_PARENT_OTHERField;
        
        private clsOntologyItem variable_ITEMTYPEField;
        
        private clsOntologyItem[] variablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public clsOntologyItem Variable_ID_ITEM {
            get {
                return this.variable_ID_ITEMField;
            }
            set {
                this.variable_ID_ITEMField = value;
                this.RaisePropertyChanged("Variable_ID_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public clsOntologyItem Variable_NAME_ITEM {
            get {
                return this.variable_NAME_ITEMField;
            }
            set {
                this.variable_NAME_ITEMField = value;
                this.RaisePropertyChanged("Variable_NAME_ITEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public clsOntologyItem Variable_ID_PARENT {
            get {
                return this.variable_ID_PARENTField;
            }
            set {
                this.variable_ID_PARENTField = value;
                this.RaisePropertyChanged("Variable_ID_PARENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public clsOntologyItem Variable_ITEMLIST {
            get {
                return this.variable_ITEMLISTField;
            }
            set {
                this.variable_ITEMLISTField = value;
                this.RaisePropertyChanged("Variable_ITEMLIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public clsOntologyItem Variable_ID_CLASS {
            get {
                return this.variable_ID_CLASSField;
            }
            set {
                this.variable_ID_CLASSField = value;
                this.RaisePropertyChanged("Variable_ID_CLASS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public clsOntologyItem Variable_ID_ATTRIBUTETYPE {
            get {
                return this.variable_ID_ATTRIBUTETYPEField;
            }
            set {
                this.variable_ID_ATTRIBUTETYPEField = value;
                this.RaisePropertyChanged("Variable_ID_ATTRIBUTETYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public clsOntologyItem Variable_ID_DATATYPE {
            get {
                return this.variable_ID_DATATYPEField;
            }
            set {
                this.variable_ID_DATATYPEField = value;
                this.RaisePropertyChanged("Variable_ID_DATATYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public clsOntologyItem Variable_MIN {
            get {
                return this.variable_MINField;
            }
            set {
                this.variable_MINField = value;
                this.RaisePropertyChanged("Variable_MIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public clsOntologyItem Variable_MAX {
            get {
                return this.variable_MAXField;
            }
            set {
                this.variable_MAXField = value;
                this.RaisePropertyChanged("Variable_MAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public clsOntologyItem Variable_ID_CLASS_LEFT {
            get {
                return this.variable_ID_CLASS_LEFTField;
            }
            set {
                this.variable_ID_CLASS_LEFTField = value;
                this.RaisePropertyChanged("Variable_ID_CLASS_LEFT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public clsOntologyItem Variable_ID_CLASS_RIGHT {
            get {
                return this.variable_ID_CLASS_RIGHTField;
            }
            set {
                this.variable_ID_CLASS_RIGHTField = value;
                this.RaisePropertyChanged("Variable_ID_CLASS_RIGHT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public clsOntologyItem Variable_ID_RELATIONTYPE {
            get {
                return this.variable_ID_RELATIONTYPEField;
            }
            set {
                this.variable_ID_RELATIONTYPEField = value;
                this.RaisePropertyChanged("Variable_ID_RELATIONTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public clsOntologyItem Variable_ONTOLOGY {
            get {
                return this.variable_ONTOLOGYField;
            }
            set {
                this.variable_ONTOLOGYField = value;
                this.RaisePropertyChanged("Variable_ONTOLOGY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public clsOntologyItem Variable_MIN_FORW {
            get {
                return this.variable_MIN_FORWField;
            }
            set {
                this.variable_MIN_FORWField = value;
                this.RaisePropertyChanged("Variable_MIN_FORW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public clsOntologyItem Variable_MAX_FORW {
            get {
                return this.variable_MAX_FORWField;
            }
            set {
                this.variable_MAX_FORWField = value;
                this.RaisePropertyChanged("Variable_MAX_FORW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public clsOntologyItem Variable_MAX_BACKW {
            get {
                return this.variable_MAX_BACKWField;
            }
            set {
                this.variable_MAX_BACKWField = value;
                this.RaisePropertyChanged("Variable_MAX_BACKW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public clsOntologyItem Variable_ID_ATTRIBUTE {
            get {
                return this.variable_ID_ATTRIBUTEField;
            }
            set {
                this.variable_ID_ATTRIBUTEField = value;
                this.RaisePropertyChanged("Variable_ID_ATTRIBUTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public clsOntologyItem Variable_ID_OBJECT {
            get {
                return this.variable_ID_OBJECTField;
            }
            set {
                this.variable_ID_OBJECTField = value;
                this.RaisePropertyChanged("Variable_ID_OBJECT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public clsOntologyItem Variable_ORDERID {
            get {
                return this.variable_ORDERIDField;
            }
            set {
                this.variable_ORDERIDField = value;
                this.RaisePropertyChanged("Variable_ORDERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public clsOntologyItem Variable_VAL_NAMED {
            get {
                return this.variable_VAL_NAMEDField;
            }
            set {
                this.variable_VAL_NAMEDField = value;
                this.RaisePropertyChanged("Variable_VAL_NAMED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public clsOntologyItem Variable_VAL_BIT {
            get {
                return this.variable_VAL_BITField;
            }
            set {
                this.variable_VAL_BITField = value;
                this.RaisePropertyChanged("Variable_VAL_BIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public clsOntologyItem Variable_VAL_DATE {
            get {
                return this.variable_VAL_DATEField;
            }
            set {
                this.variable_VAL_DATEField = value;
                this.RaisePropertyChanged("Variable_VAL_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public clsOntologyItem Variable_VAL_DOUBLE {
            get {
                return this.variable_VAL_DOUBLEField;
            }
            set {
                this.variable_VAL_DOUBLEField = value;
                this.RaisePropertyChanged("Variable_VAL_DOUBLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public clsOntologyItem Variable_VAL_LNG {
            get {
                return this.variable_VAL_LNGField;
            }
            set {
                this.variable_VAL_LNGField = value;
                this.RaisePropertyChanged("Variable_VAL_LNG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public clsOntologyItem Variable_VAL_STRING {
            get {
                return this.variable_VAL_STRINGField;
            }
            set {
                this.variable_VAL_STRINGField = value;
                this.RaisePropertyChanged("Variable_VAL_STRING");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public clsOntologyItem Variable_ID_PARENT_OBJECT {
            get {
                return this.variable_ID_PARENT_OBJECTField;
            }
            set {
                this.variable_ID_PARENT_OBJECTField = value;
                this.RaisePropertyChanged("Variable_ID_PARENT_OBJECT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public clsOntologyItem Variable_ID_OTHER {
            get {
                return this.variable_ID_OTHERField;
            }
            set {
                this.variable_ID_OTHERField = value;
                this.RaisePropertyChanged("Variable_ID_OTHER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public clsOntologyItem Variable_ID_PARENT_OTHER {
            get {
                return this.variable_ID_PARENT_OTHERField;
            }
            set {
                this.variable_ID_PARENT_OTHERField = value;
                this.RaisePropertyChanged("Variable_ID_PARENT_OTHER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public clsOntologyItem Variable_ITEMTYPE {
            get {
                return this.variable_ITEMTYPEField;
            }
            set {
                this.variable_ITEMTYPEField = value;
                this.RaisePropertyChanged("Variable_ITEMTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=29)]
        public clsOntologyItem[] Variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
                this.RaisePropertyChanged("Variables");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsOntologyRelationRules : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clsOntologyItem rule_ChildTokenField;
        
        private clsOntologyItem rule_InnerJoinField;
        
        private clsOntologyItem rule_LeftOuterJoinField;
        
        private clsOntologyItem rule_OnlyItemField;
        
        private clsOntologyItem rule_RelationBreakField;
        
        private clsOntologyItem rule_RightOuterJoinField;
        
        private clsOntologyItem rule_NoOtherRelationsOfThisTypeField;
        
        private clsOntologyItem[] ontologyRelationRulesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public clsOntologyItem Rule_ChildToken {
            get {
                return this.rule_ChildTokenField;
            }
            set {
                this.rule_ChildTokenField = value;
                this.RaisePropertyChanged("Rule_ChildToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public clsOntologyItem Rule_InnerJoin {
            get {
                return this.rule_InnerJoinField;
            }
            set {
                this.rule_InnerJoinField = value;
                this.RaisePropertyChanged("Rule_InnerJoin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public clsOntologyItem Rule_LeftOuterJoin {
            get {
                return this.rule_LeftOuterJoinField;
            }
            set {
                this.rule_LeftOuterJoinField = value;
                this.RaisePropertyChanged("Rule_LeftOuterJoin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public clsOntologyItem Rule_OnlyItem {
            get {
                return this.rule_OnlyItemField;
            }
            set {
                this.rule_OnlyItemField = value;
                this.RaisePropertyChanged("Rule_OnlyItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public clsOntologyItem Rule_RelationBreak {
            get {
                return this.rule_RelationBreakField;
            }
            set {
                this.rule_RelationBreakField = value;
                this.RaisePropertyChanged("Rule_RelationBreak");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public clsOntologyItem Rule_RightOuterJoin {
            get {
                return this.rule_RightOuterJoinField;
            }
            set {
                this.rule_RightOuterJoinField = value;
                this.RaisePropertyChanged("Rule_RightOuterJoin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public clsOntologyItem Rule_NoOtherRelationsOfThisType {
            get {
                return this.rule_NoOtherRelationsOfThisTypeField;
            }
            set {
                this.rule_NoOtherRelationsOfThisTypeField = value;
                this.RaisePropertyChanged("Rule_NoOtherRelationsOfThisType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public clsOntologyItem[] OntologyRelationRules {
            get {
                return this.ontologyRelationRulesField;
            }
            set {
                this.ontologyRelationRulesField = value;
                this.RaisePropertyChanged("OntologyRelationRules");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsMappingRules : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clsOntologyItem mappingRule_RemoveSrcField;
        
        private clsOntologyItem mappingRule_NewItemField;
        
        private clsOntologyItem mappingRule_SrcItemIsDstItemField;
        
        private clsOntologyItem[] mappingRulesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public clsOntologyItem MappingRule_RemoveSrc {
            get {
                return this.mappingRule_RemoveSrcField;
            }
            set {
                this.mappingRule_RemoveSrcField = value;
                this.RaisePropertyChanged("MappingRule_RemoveSrc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public clsOntologyItem MappingRule_NewItem {
            get {
                return this.mappingRule_NewItemField;
            }
            set {
                this.mappingRule_NewItemField = value;
                this.RaisePropertyChanged("MappingRule_NewItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public clsOntologyItem MappingRule_SrcItemIsDstItem {
            get {
                return this.mappingRule_SrcItemIsDstItemField;
            }
            set {
                this.mappingRule_SrcItemIsDstItemField = value;
                this.RaisePropertyChanged("MappingRule_SrcItemIsDstItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public clsOntologyItem[] MappingRules {
            get {
                return this.mappingRulesField;
            }
            set {
                this.mappingRulesField = value;
                this.RaisePropertyChanged("MappingRules");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OServiceConfigurationSoapChannel : WpfOnt.OServiceConfiguration.OServiceConfigurationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OServiceConfigurationSoapClient : System.ServiceModel.ClientBase<WpfOnt.OServiceConfiguration.OServiceConfigurationSoap>, WpfOnt.OServiceConfiguration.OServiceConfigurationSoap {
        
        public OServiceConfigurationSoapClient() {
        }
        
        public OServiceConfigurationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OServiceConfigurationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceConfigurationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceConfigurationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Type_Object() {
            return base.Channel.Type_Object();
        }
        
        public System.Threading.Tasks.Task<string> Type_ObjectAsync() {
            return base.Channel.Type_ObjectAsync();
        }
        
        public string Type_Class() {
            return base.Channel.Type_Class();
        }
        
        public System.Threading.Tasks.Task<string> Type_ClassAsync() {
            return base.Channel.Type_ClassAsync();
        }
        
        public string Type_AttributeType() {
            return base.Channel.Type_AttributeType();
        }
        
        public System.Threading.Tasks.Task<string> Type_AttributeTypeAsync() {
            return base.Channel.Type_AttributeTypeAsync();
        }
        
        public string Type_RelationType() {
            return base.Channel.Type_RelationType();
        }
        
        public System.Threading.Tasks.Task<string> Type_RelationTypeAsync() {
            return base.Channel.Type_RelationTypeAsync();
        }
        
        public WpfOnt.OServiceConfiguration.clsLogStates OLogStates() {
            return base.Channel.OLogStates();
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsLogStates> OLogStatesAsync() {
            return base.Channel.OLogStatesAsync();
        }
        
        public WpfOnt.OServiceConfiguration.clsMappingRules OMappingRules() {
            return base.Channel.OMappingRules();
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsMappingRules> OMappingRulesAsync() {
            return base.Channel.OMappingRulesAsync();
        }
        
        public WpfOnt.OServiceConfiguration.clsOntologyRelationRules ORelationRules() {
            return base.Channel.ORelationRules();
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsOntologyRelationRules> ORelationRulesAsync() {
            return base.Channel.ORelationRulesAsync();
        }
        
        public WpfOnt.OServiceConfiguration.clsVariables OVariables() {
            return base.Channel.OVariables();
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsVariables> OVariablesAsync() {
            return base.Channel.OVariablesAsync();
        }
        
        public WpfOnt.OServiceConfiguration.clsDirections ODirections() {
            return base.Channel.ODirections();
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsDirections> ODirectionsAsync() {
            return base.Channel.ODirectionsAsync();
        }
        
        public WpfOnt.OServiceConfiguration.clsFields OFields() {
            return base.Channel.OFields();
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.clsFields> OFieldsAsync() {
            return base.Channel.OFieldsAsync();
        }
        
        public WpfOnt.OServiceConfiguration.Config[] Config() {
            return base.Channel.Config();
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceConfiguration.Config[]> ConfigAsync() {
            return base.Channel.ConfigAsync();
        }
        
        public string RegExGuid() {
            return base.Channel.RegExGuid();
        }
        
        public System.Threading.Tasks.Task<string> RegExGuidAsync() {
            return base.Channel.RegExGuidAsync();
        }
    }
}
