//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOnt.OServiceObjectAtt {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfClsObjectAtt", Namespace="http://tempuri.org/", ItemName="clsObjectAtt")]
    [System.SerializableAttribute()]
    public class ArrayOfClsObjectAtt : System.Collections.Generic.List<WpfOnt.OServiceObjectAtt.clsObjectAtt> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsObjectAtt", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class clsObjectAtt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_AttributeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_AttributeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_AttributeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Val_NamedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Val_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_DataTypeField;
        
        private System.Nullable<bool> Val_BoolField;
        
        private System.Nullable<bool> Val_BitField;
        
        private System.Nullable<long> Val_IntField;
        
        private System.Nullable<long> Val_LngField;
        
        private System.Nullable<System.DateTime> Val_DatetimeField;
        
        private System.Nullable<double> Val_RealField;
        
        private System.Nullable<double> Val_DoubleField;
        
        private System.Nullable<System.DateTime> Val_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Val_StringField;
        
        private System.Nullable<long> OrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID_Attribute {
            get {
                return this.ID_AttributeField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_AttributeField, value) != true)) {
                    this.ID_AttributeField = value;
                    this.RaisePropertyChanged("ID_Attribute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID_AttributeType {
            get {
                return this.ID_AttributeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_AttributeTypeField, value) != true)) {
                    this.ID_AttributeTypeField = value;
                    this.RaisePropertyChanged("ID_AttributeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name_AttributeType {
            get {
                return this.Name_AttributeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_AttributeTypeField, value) != true)) {
                    this.Name_AttributeTypeField = value;
                    this.RaisePropertyChanged("Name_AttributeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ID_Object {
            get {
                return this.ID_ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_ObjectField, value) != true)) {
                    this.ID_ObjectField = value;
                    this.RaisePropertyChanged("ID_Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Name_Object {
            get {
                return this.Name_ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_ObjectField, value) != true)) {
                    this.Name_ObjectField = value;
                    this.RaisePropertyChanged("Name_Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ID_Class {
            get {
                return this.ID_ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_ClassField, value) != true)) {
                    this.ID_ClassField = value;
                    this.RaisePropertyChanged("ID_Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Name_Class {
            get {
                return this.Name_ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_ClassField, value) != true)) {
                    this.Name_ClassField = value;
                    this.RaisePropertyChanged("Name_Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Val_Named {
            get {
                return this.Val_NamedField;
            }
            set {
                if ((object.ReferenceEquals(this.Val_NamedField, value) != true)) {
                    this.Val_NamedField = value;
                    this.RaisePropertyChanged("Val_Named");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Val_Name {
            get {
                return this.Val_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Val_NameField, value) != true)) {
                    this.Val_NameField = value;
                    this.RaisePropertyChanged("Val_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ID_DataType {
            get {
                return this.ID_DataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_DataTypeField, value) != true)) {
                    this.ID_DataTypeField = value;
                    this.RaisePropertyChanged("ID_DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Name_DataType {
            get {
                return this.Name_DataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_DataTypeField, value) != true)) {
                    this.Name_DataTypeField = value;
                    this.RaisePropertyChanged("Name_DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<bool> Val_Bool {
            get {
                return this.Val_BoolField;
            }
            set {
                if ((this.Val_BoolField.Equals(value) != true)) {
                    this.Val_BoolField = value;
                    this.RaisePropertyChanged("Val_Bool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<bool> Val_Bit {
            get {
                return this.Val_BitField;
            }
            set {
                if ((this.Val_BitField.Equals(value) != true)) {
                    this.Val_BitField = value;
                    this.RaisePropertyChanged("Val_Bit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<long> Val_Int {
            get {
                return this.Val_IntField;
            }
            set {
                if ((this.Val_IntField.Equals(value) != true)) {
                    this.Val_IntField = value;
                    this.RaisePropertyChanged("Val_Int");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<long> Val_Lng {
            get {
                return this.Val_LngField;
            }
            set {
                if ((this.Val_LngField.Equals(value) != true)) {
                    this.Val_LngField = value;
                    this.RaisePropertyChanged("Val_Lng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<System.DateTime> Val_Datetime {
            get {
                return this.Val_DatetimeField;
            }
            set {
                if ((this.Val_DatetimeField.Equals(value) != true)) {
                    this.Val_DatetimeField = value;
                    this.RaisePropertyChanged("Val_Datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.Nullable<double> Val_Real {
            get {
                return this.Val_RealField;
            }
            set {
                if ((this.Val_RealField.Equals(value) != true)) {
                    this.Val_RealField = value;
                    this.RaisePropertyChanged("Val_Real");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<double> Val_Double {
            get {
                return this.Val_DoubleField;
            }
            set {
                if ((this.Val_DoubleField.Equals(value) != true)) {
                    this.Val_DoubleField = value;
                    this.RaisePropertyChanged("Val_Double");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<System.DateTime> Val_Date {
            get {
                return this.Val_DateField;
            }
            set {
                if ((this.Val_DateField.Equals(value) != true)) {
                    this.Val_DateField = value;
                    this.RaisePropertyChanged("Val_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Val_String {
            get {
                return this.Val_StringField;
            }
            set {
                if ((object.ReferenceEquals(this.Val_StringField, value) != true)) {
                    this.Val_StringField = value;
                    this.RaisePropertyChanged("Val_String");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<long> OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OServiceObjectAtt.OServiceObjectAttSoap")]
    public interface OServiceObjectAttSoap {
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname ObjectAttsResult aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAtts", ReplyAction="*")]
        WpfOnt.OServiceObjectAtt.ObjectAttsResponse ObjectAtts(WpfOnt.OServiceObjectAtt.ObjectAttsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAtts", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsResponse> ObjectAttsAsync(WpfOnt.OServiceObjectAtt.ObjectAttsRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname idObject aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdObject", ReplyAction="*")]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectResponse ObjectAttsByIdObject(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdObject", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectResponse> ObjectAttsByIdObjectAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname idClass aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdClass", ReplyAction="*")]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassResponse ObjectAttsByIdClass(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdClass", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassResponse> ObjectAttsByIdClassAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname idAttributeType aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdAttributeType", ReplyAction="*")]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeResponse ObjectAttsByIdAttributeType(WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdAttributeType", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeResponse> ObjectAttsByIdAttributeTypeAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname idObject aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdObjectAndIdAttributeType", ReplyAction="*")]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeResponse ObjectAttsByIdObjectAndIdAttributeType(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdObjectAndIdAttributeType", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeResponse> ObjectAttsByIdObjectAndIdAttributeTypeAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname idClass aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdClassAndIdAttributeType", ReplyAction="*")]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeResponse ObjectAttsByIdClassAndIdAttributeType(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdClassAndIdAttributeType", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeResponse> ObjectAttsByIdClassAndIdAttributeTypeAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname idClass aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountObjectAttsByIdClassAndIdAttributeType", ReplyAction="*")]
        WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeResponse CountObjectAttsByIdClassAndIdAttributeType(WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountObjectAttsByIdClassAndIdAttributeType", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeResponse> CountObjectAttsByIdClassAndIdAttributeTypeAsync(WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname idObject aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdObjectAndIdDataType", ReplyAction="*")]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeResponse ObjectAttsByIdObjectAndIdDataType(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdObjectAndIdDataType", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeResponse> ObjectAttsByIdObjectAndIdDataTypeAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname idClass aus Namespace http://tempuri.org/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdClassAndIdDataType", ReplyAction="*")]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeResponse ObjectAttsByIdClassAndIdDataType(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObjectAttsByIdClassAndIdDataType", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeResponse> ObjectAttsByIdClassAndIdDataTypeAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAtts", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsRequestBody Body;
        
        public ObjectAttsRequest() {
        }
        
        public ObjectAttsRequest(WpfOnt.OServiceObjectAtt.ObjectAttsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool onlyIds;
        
        public ObjectAttsRequestBody() {
        }
        
        public ObjectAttsRequestBody(bool onlyIds) {
            this.onlyIds = onlyIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsResponseBody Body;
        
        public ObjectAttsResponse() {
        }
        
        public ObjectAttsResponse(WpfOnt.OServiceObjectAtt.ObjectAttsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsResult;
        
        public ObjectAttsResponseBody() {
        }
        
        public ObjectAttsResponseBody(WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsResult) {
            this.ObjectAttsResult = ObjectAttsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdObject", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequestBody Body;
        
        public ObjectAttsByIdObjectRequest() {
        }
        
        public ObjectAttsByIdObjectRequest(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdObjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool onlyIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idObject;
        
        public ObjectAttsByIdObjectRequestBody() {
        }
        
        public ObjectAttsByIdObjectRequestBody(bool onlyIds, string idObject) {
            this.onlyIds = onlyIds;
            this.idObject = idObject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdObjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectResponseBody Body;
        
        public ObjectAttsByIdObjectResponse() {
        }
        
        public ObjectAttsByIdObjectResponse(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdObjectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdObjectResult;
        
        public ObjectAttsByIdObjectResponseBody() {
        }
        
        public ObjectAttsByIdObjectResponseBody(WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdObjectResult) {
            this.ObjectAttsByIdObjectResult = ObjectAttsByIdObjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdClassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdClass", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequestBody Body;
        
        public ObjectAttsByIdClassRequest() {
        }
        
        public ObjectAttsByIdClassRequest(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdClassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool onlyIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idClass;
        
        public ObjectAttsByIdClassRequestBody() {
        }
        
        public ObjectAttsByIdClassRequestBody(bool onlyIds, string idClass) {
            this.onlyIds = onlyIds;
            this.idClass = idClass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdClassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdClassResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassResponseBody Body;
        
        public ObjectAttsByIdClassResponse() {
        }
        
        public ObjectAttsByIdClassResponse(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdClassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdClassResult;
        
        public ObjectAttsByIdClassResponseBody() {
        }
        
        public ObjectAttsByIdClassResponseBody(WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdClassResult) {
            this.ObjectAttsByIdClassResult = ObjectAttsByIdClassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdAttributeTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdAttributeType", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequestBody Body;
        
        public ObjectAttsByIdAttributeTypeRequest() {
        }
        
        public ObjectAttsByIdAttributeTypeRequest(WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdAttributeTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool onlyIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idAttributeType;
        
        public ObjectAttsByIdAttributeTypeRequestBody() {
        }
        
        public ObjectAttsByIdAttributeTypeRequestBody(bool onlyIds, string idAttributeType) {
            this.onlyIds = onlyIds;
            this.idAttributeType = idAttributeType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdAttributeTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdAttributeTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeResponseBody Body;
        
        public ObjectAttsByIdAttributeTypeResponse() {
        }
        
        public ObjectAttsByIdAttributeTypeResponse(WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdAttributeTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdAttributeTypeResult;
        
        public ObjectAttsByIdAttributeTypeResponseBody() {
        }
        
        public ObjectAttsByIdAttributeTypeResponseBody(WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdAttributeTypeResult) {
            this.ObjectAttsByIdAttributeTypeResult = ObjectAttsByIdAttributeTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdObjectAndIdAttributeTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdObjectAndIdAttributeType", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequestBody Body;
        
        public ObjectAttsByIdObjectAndIdAttributeTypeRequest() {
        }
        
        public ObjectAttsByIdObjectAndIdAttributeTypeRequest(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdObjectAndIdAttributeTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool onlyIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idAttributeType;
        
        public ObjectAttsByIdObjectAndIdAttributeTypeRequestBody() {
        }
        
        public ObjectAttsByIdObjectAndIdAttributeTypeRequestBody(bool onlyIds, string idObject, string idAttributeType) {
            this.onlyIds = onlyIds;
            this.idObject = idObject;
            this.idAttributeType = idAttributeType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdObjectAndIdAttributeTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdObjectAndIdAttributeTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeResponseBody Body;
        
        public ObjectAttsByIdObjectAndIdAttributeTypeResponse() {
        }
        
        public ObjectAttsByIdObjectAndIdAttributeTypeResponse(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdObjectAndIdAttributeTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdObjectAndIdAttributeTypeResult;
        
        public ObjectAttsByIdObjectAndIdAttributeTypeResponseBody() {
        }
        
        public ObjectAttsByIdObjectAndIdAttributeTypeResponseBody(WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdObjectAndIdAttributeTypeResult) {
            this.ObjectAttsByIdObjectAndIdAttributeTypeResult = ObjectAttsByIdObjectAndIdAttributeTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdClassAndIdAttributeTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdClassAndIdAttributeType", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequestBody Body;
        
        public ObjectAttsByIdClassAndIdAttributeTypeRequest() {
        }
        
        public ObjectAttsByIdClassAndIdAttributeTypeRequest(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdClassAndIdAttributeTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool onlyIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idAttributeType;
        
        public ObjectAttsByIdClassAndIdAttributeTypeRequestBody() {
        }
        
        public ObjectAttsByIdClassAndIdAttributeTypeRequestBody(bool onlyIds, string idClass, string idAttributeType) {
            this.onlyIds = onlyIds;
            this.idClass = idClass;
            this.idAttributeType = idAttributeType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdClassAndIdAttributeTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdClassAndIdAttributeTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeResponseBody Body;
        
        public ObjectAttsByIdClassAndIdAttributeTypeResponse() {
        }
        
        public ObjectAttsByIdClassAndIdAttributeTypeResponse(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdClassAndIdAttributeTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdClassAndIdAttributeTypeResult;
        
        public ObjectAttsByIdClassAndIdAttributeTypeResponseBody() {
        }
        
        public ObjectAttsByIdClassAndIdAttributeTypeResponseBody(WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdClassAndIdAttributeTypeResult) {
            this.ObjectAttsByIdClassAndIdAttributeTypeResult = ObjectAttsByIdClassAndIdAttributeTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountObjectAttsByIdClassAndIdAttributeTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountObjectAttsByIdClassAndIdAttributeType", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequestBody Body;
        
        public CountObjectAttsByIdClassAndIdAttributeTypeRequest() {
        }
        
        public CountObjectAttsByIdClassAndIdAttributeTypeRequest(WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CountObjectAttsByIdClassAndIdAttributeTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idAttributeType;
        
        public CountObjectAttsByIdClassAndIdAttributeTypeRequestBody() {
        }
        
        public CountObjectAttsByIdClassAndIdAttributeTypeRequestBody(string idClass, string idAttributeType) {
            this.idClass = idClass;
            this.idAttributeType = idAttributeType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountObjectAttsByIdClassAndIdAttributeTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountObjectAttsByIdClassAndIdAttributeTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeResponseBody Body;
        
        public CountObjectAttsByIdClassAndIdAttributeTypeResponse() {
        }
        
        public CountObjectAttsByIdClassAndIdAttributeTypeResponse(WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CountObjectAttsByIdClassAndIdAttributeTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long CountObjectAttsByIdClassAndIdAttributeTypeResult;
        
        public CountObjectAttsByIdClassAndIdAttributeTypeResponseBody() {
        }
        
        public CountObjectAttsByIdClassAndIdAttributeTypeResponseBody(long CountObjectAttsByIdClassAndIdAttributeTypeResult) {
            this.CountObjectAttsByIdClassAndIdAttributeTypeResult = CountObjectAttsByIdClassAndIdAttributeTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdObjectAndIdDataTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdObjectAndIdDataType", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequestBody Body;
        
        public ObjectAttsByIdObjectAndIdDataTypeRequest() {
        }
        
        public ObjectAttsByIdObjectAndIdDataTypeRequest(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdObjectAndIdDataTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool onlyIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idDataType;
        
        public ObjectAttsByIdObjectAndIdDataTypeRequestBody() {
        }
        
        public ObjectAttsByIdObjectAndIdDataTypeRequestBody(bool onlyIds, string idObject, string idDataType) {
            this.onlyIds = onlyIds;
            this.idObject = idObject;
            this.idDataType = idDataType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdObjectAndIdDataTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdObjectAndIdDataTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeResponseBody Body;
        
        public ObjectAttsByIdObjectAndIdDataTypeResponse() {
        }
        
        public ObjectAttsByIdObjectAndIdDataTypeResponse(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdObjectAndIdDataTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdObjectAndIdDataTypeResult;
        
        public ObjectAttsByIdObjectAndIdDataTypeResponseBody() {
        }
        
        public ObjectAttsByIdObjectAndIdDataTypeResponseBody(WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdObjectAndIdDataTypeResult) {
            this.ObjectAttsByIdObjectAndIdDataTypeResult = ObjectAttsByIdObjectAndIdDataTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdClassAndIdDataTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdClassAndIdDataType", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequestBody Body;
        
        public ObjectAttsByIdClassAndIdDataTypeRequest() {
        }
        
        public ObjectAttsByIdClassAndIdDataTypeRequest(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdClassAndIdDataTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool onlyIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idDataType;
        
        public ObjectAttsByIdClassAndIdDataTypeRequestBody() {
        }
        
        public ObjectAttsByIdClassAndIdDataTypeRequestBody(bool onlyIds, string idClass, string idDataType) {
            this.onlyIds = onlyIds;
            this.idClass = idClass;
            this.idDataType = idDataType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObjectAttsByIdClassAndIdDataTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObjectAttsByIdClassAndIdDataTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeResponseBody Body;
        
        public ObjectAttsByIdClassAndIdDataTypeResponse() {
        }
        
        public ObjectAttsByIdClassAndIdDataTypeResponse(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectAttsByIdClassAndIdDataTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdClassAndIdDataTypeResult;
        
        public ObjectAttsByIdClassAndIdDataTypeResponseBody() {
        }
        
        public ObjectAttsByIdClassAndIdDataTypeResponseBody(WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdClassAndIdDataTypeResult) {
            this.ObjectAttsByIdClassAndIdDataTypeResult = ObjectAttsByIdClassAndIdDataTypeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OServiceObjectAttSoapChannel : WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OServiceObjectAttSoapClient : System.ServiceModel.ClientBase<WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap>, WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap {
        
        public OServiceObjectAttSoapClient() {
        }
        
        public OServiceObjectAttSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OServiceObjectAttSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceObjectAttSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OServiceObjectAttSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceObjectAtt.ObjectAttsResponse WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAtts(WpfOnt.OServiceObjectAtt.ObjectAttsRequest request) {
            return base.Channel.ObjectAtts(request);
        }
        
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAtts(bool onlyIds) {
            WpfOnt.OServiceObjectAtt.ObjectAttsRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsRequestBody();
            inValue.Body.onlyIds = onlyIds;
            WpfOnt.OServiceObjectAtt.ObjectAttsResponse retVal = ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAtts(inValue);
            return retVal.Body.ObjectAttsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsResponse> WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsAsync(WpfOnt.OServiceObjectAtt.ObjectAttsRequest request) {
            return base.Channel.ObjectAttsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsResponse> ObjectAttsAsync(bool onlyIds) {
            WpfOnt.OServiceObjectAtt.ObjectAttsRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsRequestBody();
            inValue.Body.onlyIds = onlyIds;
            return ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectResponse WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdObject(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequest request) {
            return base.Channel.ObjectAttsByIdObject(request);
        }
        
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdObject(bool onlyIds, string idObject) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idObject = idObject;
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectResponse retVal = ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdObject(inValue);
            return retVal.Body.ObjectAttsByIdObjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectResponse> WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdObjectAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequest request) {
            return base.Channel.ObjectAttsByIdObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectResponse> ObjectAttsByIdObjectAsync(bool onlyIds, string idObject) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idObject = idObject;
            return ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdObjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassResponse WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdClass(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequest request) {
            return base.Channel.ObjectAttsByIdClass(request);
        }
        
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdClass(bool onlyIds, string idClass) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idClass = idClass;
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassResponse retVal = ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdClass(inValue);
            return retVal.Body.ObjectAttsByIdClassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassResponse> WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdClassAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequest request) {
            return base.Channel.ObjectAttsByIdClassAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassResponse> ObjectAttsByIdClassAsync(bool onlyIds, string idClass) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idClass = idClass;
            return ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdClassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeResponse WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdAttributeType(WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequest request) {
            return base.Channel.ObjectAttsByIdAttributeType(request);
        }
        
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdAttributeType(bool onlyIds, string idAttributeType) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idAttributeType = idAttributeType;
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeResponse retVal = ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdAttributeType(inValue);
            return retVal.Body.ObjectAttsByIdAttributeTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeResponse> WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdAttributeTypeAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequest request) {
            return base.Channel.ObjectAttsByIdAttributeTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeResponse> ObjectAttsByIdAttributeTypeAsync(bool onlyIds, string idAttributeType) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdAttributeTypeRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idAttributeType = idAttributeType;
            return ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdAttributeTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeResponse WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdObjectAndIdAttributeType(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequest request) {
            return base.Channel.ObjectAttsByIdObjectAndIdAttributeType(request);
        }
        
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdObjectAndIdAttributeType(bool onlyIds, string idObject, string idAttributeType) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idObject = idObject;
            inValue.Body.idAttributeType = idAttributeType;
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeResponse retVal = ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdObjectAndIdAttributeType(inValue);
            return retVal.Body.ObjectAttsByIdObjectAndIdAttributeTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeResponse> WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdObjectAndIdAttributeTypeAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequest request) {
            return base.Channel.ObjectAttsByIdObjectAndIdAttributeTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeResponse> ObjectAttsByIdObjectAndIdAttributeTypeAsync(bool onlyIds, string idObject, string idAttributeType) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdAttributeTypeRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idObject = idObject;
            inValue.Body.idAttributeType = idAttributeType;
            return ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdObjectAndIdAttributeTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeResponse WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdClassAndIdAttributeType(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequest request) {
            return base.Channel.ObjectAttsByIdClassAndIdAttributeType(request);
        }
        
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdClassAndIdAttributeType(bool onlyIds, string idClass, string idAttributeType) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idClass = idClass;
            inValue.Body.idAttributeType = idAttributeType;
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeResponse retVal = ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdClassAndIdAttributeType(inValue);
            return retVal.Body.ObjectAttsByIdClassAndIdAttributeTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeResponse> WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdClassAndIdAttributeTypeAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequest request) {
            return base.Channel.ObjectAttsByIdClassAndIdAttributeTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeResponse> ObjectAttsByIdClassAndIdAttributeTypeAsync(bool onlyIds, string idClass, string idAttributeType) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdAttributeTypeRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idClass = idClass;
            inValue.Body.idAttributeType = idAttributeType;
            return ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdClassAndIdAttributeTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeResponse WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.CountObjectAttsByIdClassAndIdAttributeType(WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequest request) {
            return base.Channel.CountObjectAttsByIdClassAndIdAttributeType(request);
        }
        
        public long CountObjectAttsByIdClassAndIdAttributeType(string idClass, string idAttributeType) {
            WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequest inValue = new WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequestBody();
            inValue.Body.idClass = idClass;
            inValue.Body.idAttributeType = idAttributeType;
            WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeResponse retVal = ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).CountObjectAttsByIdClassAndIdAttributeType(inValue);
            return retVal.Body.CountObjectAttsByIdClassAndIdAttributeTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeResponse> WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.CountObjectAttsByIdClassAndIdAttributeTypeAsync(WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequest request) {
            return base.Channel.CountObjectAttsByIdClassAndIdAttributeTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeResponse> CountObjectAttsByIdClassAndIdAttributeTypeAsync(string idClass, string idAttributeType) {
            WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequest inValue = new WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.CountObjectAttsByIdClassAndIdAttributeTypeRequestBody();
            inValue.Body.idClass = idClass;
            inValue.Body.idAttributeType = idAttributeType;
            return ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).CountObjectAttsByIdClassAndIdAttributeTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeResponse WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdObjectAndIdDataType(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequest request) {
            return base.Channel.ObjectAttsByIdObjectAndIdDataType(request);
        }
        
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdObjectAndIdDataType(bool onlyIds, string idObject, string idDataType) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idObject = idObject;
            inValue.Body.idDataType = idDataType;
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeResponse retVal = ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdObjectAndIdDataType(inValue);
            return retVal.Body.ObjectAttsByIdObjectAndIdDataTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeResponse> WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdObjectAndIdDataTypeAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequest request) {
            return base.Channel.ObjectAttsByIdObjectAndIdDataTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeResponse> ObjectAttsByIdObjectAndIdDataTypeAsync(bool onlyIds, string idObject, string idDataType) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdObjectAndIdDataTypeRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idObject = idObject;
            inValue.Body.idDataType = idDataType;
            return ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdObjectAndIdDataTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeResponse WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdClassAndIdDataType(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequest request) {
            return base.Channel.ObjectAttsByIdClassAndIdDataType(request);
        }
        
        public WpfOnt.OServiceObjectAtt.ArrayOfClsObjectAtt ObjectAttsByIdClassAndIdDataType(bool onlyIds, string idClass, string idDataType) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idClass = idClass;
            inValue.Body.idDataType = idDataType;
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeResponse retVal = ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdClassAndIdDataType(inValue);
            return retVal.Body.ObjectAttsByIdClassAndIdDataTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeResponse> WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap.ObjectAttsByIdClassAndIdDataTypeAsync(WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequest request) {
            return base.Channel.ObjectAttsByIdClassAndIdDataTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeResponse> ObjectAttsByIdClassAndIdDataTypeAsync(bool onlyIds, string idClass, string idDataType) {
            WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequest inValue = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequest();
            inValue.Body = new WpfOnt.OServiceObjectAtt.ObjectAttsByIdClassAndIdDataTypeRequestBody();
            inValue.Body.onlyIds = onlyIds;
            inValue.Body.idClass = idClass;
            inValue.Body.idDataType = idDataType;
            return ((WpfOnt.OServiceObjectAtt.OServiceObjectAttSoap)(this)).ObjectAttsByIdClassAndIdDataTypeAsync(inValue);
        }
    }
}
